
[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["Aldo Cortesi <aldo@corte.si>"]
description = "AI-assisted coding for rust"
license = "MIT"
repository = "https://github.com/cortesi/tenx"
keywords = ["ai"]

[workspace]
resolver = "2"
members = ["crates/*"]

