project = "rust/evenmedian"
desc = "A simple problem that won't be a simple recitation from memory."

[op.ask]
prompt = "Complete the evenmedian function."
editable = ["**/code.rs"]

[config]
no_preflight = true
