project = "rust/evenmedian"
desc = "A simple problem that won't be a simple recitation from memory, blind variation."

[op.ask]
prompt = "Complete the evenmedian function."
editable = []

[config]
no_preflight = true
