#!/bin/sh
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
RUN="cargo run -- --session-store-dir $SCRIPT_DIR/.session_store"

cd $SCRIPT_DIR/..
$RUN new
$RUN edit \
    --prompt "Please complete the fibonacci function" \
    ./samples/simple/src/*.rs 
$RUN sess --full
git diff samples/simple
git checkout samples/simple
