[package]
name = "tenx"
edition = "2021"

version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive", "env"] }
colored = "2.1.0"
futures-util = "0.3.30"
libtenx = { workspace=true }
misanthropy = "0.0.6"
tempfile = "3.12.0"
tokio = { version = "1.39.2", features = ["full"] }
