#!/bin/sh

cargo run --release --bin ttrial --  \
    run -n 3 \
    --resume \
    --save ./tmp/trial1 \
    --model deepseek \
    --model gpt4o \
    --model gpt4o-mini \
    --model sonnet \
    --model haiku \
    --model qwen \
    --model llama-70b \
    --model grok \
    --model llama-8b-turbo \
    --model o1-mini \
    --model o1 \
    "*" 


