[package]
name = "libtenx"
edition = "2021"

version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
misanthropy = { path = "../../../misanthropy/crates/misanthropy" }

libruskel = "0.0.6"
quick-xml = "0.36.1"
tempfile = "3.11.0"
thiserror = "1.0.63"
walkdir = "2.5.0"
tracing = "0.1.40"
serde = { version = "1.0.205", features = ["derive"] }
tokio = "1.39.2"
async-trait = "0.1.81"
dirs = "5.0.1"
serde_json = "1.0.124"
colored = "2.1.0"

[dev-dependencies]
indoc = "2.0.5"
pretty_assertions = "1.4.0"
